### ISSUE TITLE
Hackport does not build on `ghc-9.2.4`

### ISSUE THREAD

**Issue by hololeap** [gentoo-haskell/hackport#102]
This currently fails seemingly because of the old version of `Cabal` it is linked against.

**Comment by solpeth** [comment]
Hmm. Internally it builds against Cabal-3.4. Is this the problem - that Cabal 3.4 cannot be built by ghc-9.2.1?

I've looked into bumping up the submodule to Cabal-3.6, and it is actually quite seamless. The only outstanding failure is upstream hackage-security has not updated its bounds on Cabal in its .cabal file, thus causing the build to fail (at least with a local `cabal v2-build`.

**Comment by l29ah** [comment]
Bump!
Can't build hackport, so i can't update hackport to handle the new ghc libs, so i can't bump dbus for ghc-9.2.4, so i can't build my xmonad config :<
