### ISSUE TITLE
Build failure with `>=base16-bytestring-1.0`

### ISSUE THREAD

**Issue by hololeap** [gentoo-haskell/hackport#105]
This is one of the last packages that is holding back unmasking `>=dev-haskell/base16-bytestring-1.0.1.0` in [`gentoo-haskell`](https://github.com/gentoo-haskell/gentoo-haskell/blob/2bdd400c6c64b8cbb7e53d83a4aa282799a8e958/profiles/package.mask#L93). See this commit and the associated Github CI failure: https://github.com/hololeap/hackport/commit/62b7a4e02df3fb3f18f9d2e5396a5818931b25d8

**Comment by solpeth** [comment]
I imagine we have to bump the cabal submodule to get this working. That's something I'm having a few difficulties with: I'm trying to find a commit to rebase onto that evades these issues. I'm nearly there.
