### ISSUE TITLE
Updating metadata.xml to reflect flag descriptions from hackage

### ISSUE THREAD

**Issue by hololeap** [gentoo-haskell/hackport#35]
I find myself doing a lot of copy-pasting of flag names and descriptions from hackage.haskell.org into my `metadata.xml` files, mostly to make `repoman` happy. It seems like it would be pretty easy to convert the flag data from hackage and add this info to `metadata.xml` automatically.

The section of the `metadata.xml` I'm talking about looks like this:

    <use>
         <flag name="buildexamples">Build examples</flag>
    </use>

**Comment by trofi** [comment]
Good suggestion! Should not be hard to implement.

**Comment by solpeth** [comment]
@hololeap this is now more or less implemented. Does this satisfy your enhancement request?

**Comment by solpeth** [comment]
I'll consider this resolved. Closing.

**Comment by hololeap** [comment]
It looks good. Thanks!
