### ISSUE TITLE
Fix escaping synopis generation on packages like tar

### ISSUE THREAD

**Issue by trofi** [gentoo-haskell/hackport#36]
See detalis on https://bugs.gentoo.org/666314#c3 where generated description is:

```
DESCRIPTION="Reading, writing and manipulating \\"
```

Could be better, something like:

```
DESCRIPTION="Reading, writing and manipulating '.tar' archives."
```

**Comment by solpeth** [comment]
I'm not sure when this changed, but this now appears to work correctly for me on hackport HEAD.

On a clean `hackport merge` of the `tar` package (having deleted it to avoid `hackport` using existing metadata) I now get:

`DESCRIPTION="Reading, writing and manipulating \".tar\" archive files"`

Is this desirable, or should the escaper in `Portage.EBuild.quote` be adjusted to remove the internal `\"`s?

**Comment by solpeth** [comment]
Closed. This seems fixed to me.

**Comment by solpeth** [comment]
I just noticed that hackport gives `dev-haskell/contravariant-extras`  a `DESCRIPTION` that does not accurately reflect that of its .cabal file.

It should be: `Extras for the \"contravariant\" package`
It is: `Extras for the \\`

This is despite test cases for `Portage.EBuild.quote` passing. Either the test cases are wrong, or something further up the chain isn't working properly.

**Comment by solpeth** [comment]
So, if it is a fresh merge with no previously existing ebuilds, the `DESCRIPTION` is correctly translated from the `.cabal` file to the ebuild.

But subsequent merges result in the `DESCRIPTION` becoming corrupted. So I think it may have something to do with our `EMeta` handling of transferring an existing description to a new ebuild.

**Comment by solpeth** [comment]
My suspicion was correct. I'll push a fix shortly, which avoids extracting a `DESCRIPTION` from an existing ebuild and transplanting it into the new one. Instead, just use the new `DESCRIPTION`.
