### ISSUE TITLE
The latest *.cabal file revision needs to be fetched before build

### ISSUE THREAD

**Issue by hololeap** [gentoo-haskell/hackport#43]
I am re-opening gentoo-haskell/gentoo-haskell#861 here.

One idea is to have hackport fetch the latest .cabal and put it in `$FILESDIR`, which could then be copied to `$WORKDIR` during the prepare phase and used for the build. It just seems like this would be a more elegant solution than `cabal_chdeps`, considering that there is more to a .cabal file than just a list of dependencies.

**Comment by solpeth** [comment]
@hololeap see also: https://github.com/gentoo-haskell/hackport/issues/30

**Comment by hololeap** [comment]
I'll close this as a duplicate of #30 .
