### ISSUE TITLE
hackport no longer working

### ISSUE THREAD

**Issue by hololeap** [gentoo-haskell/hackport#45]
No matter what, `hackport` fails when I try to use `merge` or `make-ebuild`. I have tried deleting `~/.hackport`, `~/.cabal`, and deleting and re-cloning `gentoo-haskell`. I have also tried using `app-portage/hackport-0.5.6` and `app-portage/hackport-9999`. Nothing seems to work. Here is the error I am getting:

    hackport: Assertion failed
    CalStack (from HasCallStack):
      assert, called at cabal/Cabal/Distribution/Simple/PackageIndex.hs:201:30 in main:Distribution.Simple.PackageIndex
      mkPackageIndex, called at cabal/Cabal/Distribution/Simple/PackageIndex.hs:215:17 in main:Distribution.Simple.PackageIndex

My guess is that the current commit of the `cabal` submodule is no longer compatible with Hackage.

**Comment by solpeth** [comment]
Which package are you trying to merge that fails?

**Comment by hololeap** [comment]
I tried several and they all failed. I haven't found one that works yet.

**Comment by solpeth** [comment]
@hololeap do you have any specific packages that failed so I can try and reproduce this? I've had no issues using hackport today.

**Comment by hololeap** [comment]
I just tried with `hackport-0.5.6`:

`synthesizer-filter`
`kan-extensions`
`lens`

All three give me the same error:
```hackport: Assertion failed
CallStack (from HasCallStack):
  assert, called at cabal/Cabal/Distribution/Simple/PackageIndex.hs:201:30 in main:Distribution.Simple.PackageIndex
  mkPackageIndex, called at cabal/Cabal/Distribution/Simple/PackageIndex.hs:215:17 in main:Distribution.Simple.PackageIndex
```

**Comment by solpeth** [comment]
@hololeap i'm sorry, I can't seem to reproduce this at all. I'll try to figure out what I can.

**Comment by hololeap** [comment]
I am also unable to reproduce this on another system. Very strange. I will investigate.

**Comment by trofi** [comment]
How about `hackport-9999`? Maybe we should just cut a new release.

**Comment by hololeap** [comment]
Yeah, I had the same issues with the live version as well. I am rebuilding everything with `ghc-8.4.4` and also `FEATURES=test` just to make sure everything is working correctly. I will then check to see if `hackport-9999` is working.

**Comment by hololeap** [comment]
This comment was in the source file that is referenced in the stack trace:

```
  -- If you see this invariant failing (ie the assert in mkPackageIndex below)
  -- then one thing to check is if it is happening in fromList. Check if the
  -- second list above (the sort [...] bit) is ending up with duplicates. This
  -- has been observed in practice once due to a messed up ghc-pkg db. How/why
-- it became messed up was not discovered.
```

([Source](https://github.com/gentoo-haskell/cabal/blob/ca15d119eac6ac93ac488fc416b36c7fad3b1139/Cabal/Distribution/Simple/PackageIndex.hs#L186-L190))

This actually lines up exactly with what is happening on my system, so apparently it could be a "messed up" ghc-pkg db... But, I don't know how to check for this or how to fix it. I unmerged everything Haskell-related before doing this latest update, so I don't see how that wouldn't reset the ghc-pkg database as well.

**Comment by hololeap** [comment]
I commented out all `CABAL_*` lines in `make.conf` as well as everything Haskell-related in `package.use` and `package.env`, unmerged everything, thoroughly scoured my system for any traces of Haskell-related stuff and removed them (I did find an orphaned directory from `ghc-8.4.3`), then ran `emerge -1 hackport`. FINALLY it works again.

I have no idea what caused this bug. I will be incrementally uncommenting my build flags and see if anything triggers it again.

**Comment by solpeth** [comment]
That's great that you found it. If you do find what the issue was I'd be interested to know in case this happens again.

**Comment by hololeap** [comment]
Well, at this point it looks like `CABAL_EXTRA_CONFIGURE_FLAGS="-O0"` was the culprit, as strange as that may seem. All of the other `package.use`, `package.env`, and `CABAL_EXTRA_CONFIGURE_FLAGS` are restored to where they are before, and I removed `-O0`. Then, I rebuilt `hackport-9999` and now it is working again.

**Comment by solpeth** [comment]
I'm going to close this @hololeap , unless you believe this should remain open. I'm glad you found the issue!
