### ISSUE TITLE
The performance penalty of shared libraries generated by hackport.

### ISSUE THREAD

**Issue by crocket** [gentoo-haskell/hackport#47]
https://wiki.haskell.org/Shared_libraries_and_GHC says haskell shared libraries are 5 ~ 20 times as slow as inlined libraries.

**Comment by trofi** [comment]
1. Haskell's ebuilds generate both static and shared libraries. You are free to use static libraries on per-package using `package.env` and `CABAL_CONFIGURE_FLAGS="--disable-shared --disable-executable-dynamic"`. But be careful: template haskell really needs haskell's shared libraries. And normally there is no real reason to disable shared libraries.

2. Inlining is not disabled by default across shared libraries. `ghc` binary itself links against shared libraries by default.

The article's reasoning applies exactly the same to static libraries. They are not different.

**Comment by crocket** [comment]
Are you saying that haskell packages created by hackport will not experience performance penalties?

**Comment by crocket** [comment]
I haven't measured performance.

**Comment by trofi** [comment]
Shared libraries should not be slow.

**Comment by crocket** [comment]
Are you saying that shared libraries used to be slow but are not slow anymore?

**Comment by trofi** [comment]
I did not say that. I'm not aware of haskell shared libraries ever being slow.

**Comment by int-e** [comment]
> https://wiki.haskell.org/Shared_libraries_and_GHC says haskell shared libraries are 5 ~ 20 times as slow as inlined libraries.

I've edited the page, but it never said that. What the page says is that not doing *inlining* would incur a 5 to 20 times slowdown. This is unacceptable, so ghc does inline heavily, even across library boundaries, and that breaks ABI compatibility between library versions.

In a nutshell we can have ABI compatibility *or* performance, but not both.
