### ISSUE TITLE
UTF-8 support

### ISSUE THREAD

**Issue by Uroc327** [gentoo-haskell/hackport#54]
When `hackport merge`ing a package, which has utf-8 characters in its hackage description, the generated `metadata.xml` is invalid.

For example with `hackport merge clash-ghc`, the 2-byte λ (`0x03bb`) will become a `0x00bb`. This byte sequence is no valid utf-8.

**Comment by solpeth** [comment]
Which version of hackport are you using?

-9999 should correctly handle utf-8.

**Comment by Uroc327** [comment]
Great to hear, thanks! I'm using 0.6 atm.

**Comment by solpeth** [comment]
@Uroc327 we could have a look at cutting a new version. I'll see what we can do.
