### ISSUE TITLE
[Feature] Teach hackport to assist in bumping major GHC versions

### ISSUE THREAD

**Issue by solpeth** [gentoo-haskell/hackport#66]
Teach `hackport` to determine the _maximum_ GHC version required by packages in `::haskell`
---

**Preamble**
Currently, to bump major GHC versions, we have to do something like the following:

1. Bump and/or mark bundled libraries in `::haskell`
2. Generate GHC binaries for bootstrapping
3. Build 75% of `::haskell`, including 'critical' packages detailed in the docs

Step 3 is consistently the biggest hurdle, in that it takes a _lot_ of time. But, of course, it is absolutely necessary to determine if `::haskell` is going to be otherwise broken by a major compiler upgrade. I did step 3 for **8.0** -> **8.4**, and again from **8.4** to **8.6**. But I would much rather if I had a build server to do this for me, as my laptop isn't going to be able to put up with it forever.

While I sort out sourcing a server to get set up on (I have considered AWS, but I haven't gotten very far with that idea), I thought that hackport may be able to help us in determining how much of `::haskell` builds with a given version of GHC.

**Proposal**
`hackport` already knows how to determine the _minimum_ version of GHC required for a package. 

- Let's re-use that functionality to determine the _maximum_ version of GHC required for a package to build.

- Let's get `hackport` to methodically work its way through `::haskell`, determining each package's maximum version (which will be based on the upper bounds of bundled libraries, such as `base` and `containers`) and writing out to a file.

- Let's parse that file to determine the percentage of packages buildable with given versions of GHC. The file should be human-readable, such that we can work through the list of non-conformant packages, while also being able to be parsed to determine percentages of packages buildable with given versions of GHC.

**Conclusion**
I've given this only a very quick look, but I believe it shouldn't be _too_ difficult to implement, given the basic plumbing is already there.

While this won't eliminate the need to physically test the build of packages, it will certainly give us a better idea of the state of `::haskell` with regards to its proportion of compatible versions of GHC. Say, for example, we had 85% of `::haskell` reporting as buildable with version `x`. That may give us the reasonable belief that, after testing critical packages for build failures, version `x` can be unmasked without going ahead and building the entirety of `::haskell`.

The use case this seems to be most applicable to is the one we are in now: we are two versions of GHC behind upstream (granted, much of hackage hasn't moved on to the latest version, **8.10.1**, either), but we are very much up to date with hackage, which hasn't always been the case.

A final word: **if there is an easier way of getting the same result as above, I'm all ears.**

**Comment by solpeth** [comment]
CC @trofi @pbarill 

Thoughts?

**Comment by trofi** [comment]
Should be fine.

On top of that we can also generate a comment of supported ghc versions right into .ebuild as well. Something like:

```
# resolved: ghc-8.4.1
# resolved: ghc-8.6.1
```

but comments will get stale over time as people tweak the depends. Still might be a good enough signal that package was not ported upstream and thus might be a candidate for removal.

**Comment by pbarill** [comment]
Wasn't sure what the compiler upgrade process is. Seems it's as simple as it gets: Build `dev-haskell/*`, take note of what goes wrong and do something if you can. So it's mostly a matter of firepower (with a side of patience).

My almost 10 years old laptop at home is no contender for this job and the main builder I use (during day time) is an ok desktop, with intermittent access (and not much access these days). I have been thinking for a while to get a refurbished workstation (better value these days than new desktops). Seems like it could be of use there, as it's the kind of machine that's made to receive pain. Shipping is a bit of an issue right now (something something virus). I also recently looked at cloud solutions, for some other projects, while thinking about use for Gentoo and Haskell. I looked at AWS and Google Platform.

I gave up fast on AWS. Too complicated offering. I just want decent specs and ssh to get in and do my stunts, not some weird over-engineered API thingy. Google Compute Engine is a bit more straightforward and they give an interesting 1-year trial (or until world domination?). You get Debian Linux (and some other choices, though no Gentoo). I think you could still manage to do some Gentoo stuff through `chroot` (better than nothing). It might be possible technically to install Gentoo and boot it on that instance, but I doubt it would be ok with the terms. That Debian ships with Google-specific daemons, and I don't think they would appreciate to have a wild untamed beast under their nose.

**Comment by solpeth** [comment]
Not to dismiss the ideas put forward above, I'm closing this as I haven't worked on it and have little intention to.

Beyond that, it is as @pbarill says rather a problem of firepower. I'm currently doing the 75% build of `::haskell` for ghc-8.8.3, which is time consuming but nonetheless something which avoids a bunch of issues that only building packages would pick up. A proxy for such testing by determining the right version bounds we want would no doubt be useful, but more firepower is ultimately what is needed here (or a server solution, which again I haven't looked into enough).
