### ISSUE TITLE
Add --refresh-metadata option

### ISSUE THREAD

**Issue by solpeth** [gentoo-haskell/hackport#68]
HackPort automatically generates the `metadata.xml` with USE flag entries for quite some time now. But if the USE flags of a package change, the maintainer must either delete the existing metadata.xml and run `hackport merge` again (and this only works if no USE flags have been deleted between versions) or the maintainer must manually edit the metadata.xml by hand.

A `--refresh-metadata` option (which is a commented `TODO` in the source code) could work like this:

1. Force an overwrite of the existing `metadata.xml`, taking into account only the current package version. It therefore may create an invalid `metadata.xml`; or
2. Overwrite the existing `metadata.xml` _except for the USE flag entries_, which will be overwritten by the union of all active USE flags across all package versions. This would be the preferred method.

**Comment by trofi** [comment]
Appending new USE flags into `metadata.xml` sounds reasonable. It would roughly match today's `KEYWORDS` propagation logic as well when we try hard to preserve all keywords and license from a previous ebuild..

**Comment by solpeth** [comment]
That's a good idea, thanks.

I may have a look at this over the next few days to see how to go about it.

**Comment by solpeth** [comment]
Rough idea:

1. Extend the `Metadata` datatype (actually a `newtype`, but convert to `data`) in `Portage/Metadata.hs` to contain `[(String,String)]`, a list of tuples of USE flags and their descriptions (or even just `[Cabal.Flag]` directly), and extend the xml parser to parse this information (also write any necessary functions to deal with transformation of data to make this work)
2. Grab the union of the current `metadata.xml`'s USE flags and those of the new one
3. Write into the `metadata.xml` if `--refresh-metadata` (or whatever name best reflects this functionality) is specified.

**Comment by trofi** [comment]
Sounds good!

**Comment by solpeth** [comment]
Quick update:

Nearly everything is in place. The only outstanding task is adding the `--refresh-metadata` flag itself, and having it switch the new functionality.

**Comment by solpeth** [comment]
@trofi , I've added a comment in my PR where I make the case for enabling this functionality by default. Based on my understanding, and given how it adds to an existing `metadata.xml` rather than overwriting it, this should actually _reduce_ the incidence of an invalid `metadata.xml` causing repoman checks to fail (in other words, good for encouraging new contributors by reducing the margin for error).

You're welcome to read my longer rationale [here](https://github.com/gentoo-haskell/hackport/pull/69#issuecomment-659065505), otherwise I look forward to your thoughts on this.

**Comment by trofi** [comment]
Yeah, having it always enabled makes total sense.
