### ISSUE TITLE
Generate BDEPEND field in ebuilds

### ISSUE THREAD

**Issue by solpeth** [gentoo-haskell/hackport#70]
EAPI 7 split `DEPEND` into `DEPEND` and `BDEPEND`. I'm not familiar with cross-compiling, but would there be any benefit to the Gentoo Haskell ecosystem in generating this split in ebuilds?

From a cursory glance it seems that the change would simply be from (**EDIT:** add `ghc` dependency under `RDEPEND` and `BDEPEND`)

```
RDEPEND="dev-lang/ghc-<version>
"
DEPEND="${RDEPEND}
    dev-haskell/cabal
    test? ( dev-haskell/quickcheck )
"
```
to

```
RDEPEND="dev-lang/ghc-<version>
"
DEPEND="${RDEPEND}"
BDEPEND="dev-haskell/cabal
    dev-lang/ghc-<version>
    test? ( dev-haskell/quickcheck )
"
```

I haven't looked at the changes required (although I don't imagine them to be extensive), but I'd be happy to give this a go if it's worthwhile.

**EDIT:** It seems to me that we would _also_ need to duplicate the dependency on `ghc` under `BDEPEND` so that the build machine has access to the compiler. To my understanding, we currently put `ghc` under `RDEPEND` due to its bundled core libraries, and since `RDEPEND` and `DEPEND` assume that they are referring to CHOST rather than CBUILD, this is not an issue if we don't utilise `BDEPEND`.

**Comment by solpeth** [comment]
cc'ing @trofi , since I think he has used `ghc` in a cross-compiling scenario before.

To add further commentary, it appears that the benefit of having a `BDEPEND` is largely squandered if we need `ghc` on `CBUILD` and `CHOST`, the former as compiler and the latter as libraries. All it would do would be to avoid installing `cabal` and test dependencies on `CHOST`, which usually aren't that heavy anyway, so the benefit as #71 stands is rather minimal. So I think if we were to implement this we should try to avoid having `ghc` on `CHOST`.

But to take `ghc` off `CHOST` (i.e. out of `RDEPEND`) would mean otherwise providing those libraries under `RDEPEND`. Whether or not those packages could conditionally be dummy packages is unclear to me. For example, in the regular, non cross-compiling scenario, with `ghc` under `BDEPEND`, If `ghc` installs both itself and its libraries for other consumers then a simple conditional check for `CHOST == CBUILD` in the `haskell-cabal.eclass` dummy packages function may suffice. But would that not make `ghc`'s libraries themselves runtime dependencies, belonging in `RDEPEND`? On the other hand, assuming we install `ghc`'s libraries so that only `ghc` links against them, we would then never provide dummy packages and instead install all libraries as normal. But this would mean having a copy of each core library twice: one for `ghc`, another for everyone else. This would surely only benefit cross-compilers who could avoid having `ghc` on both `CBUILD` and `CHOST`, but negatively affect non cross-compilers who would have two identical copies of libraries installed on their system (or perhaps this would free us up to upgrade core libraries more freely, although their rigidity hasn't been a problem for me before).

We would also have to add packages which we currently silently depend on through the existence of `ghc` on `CHOST`. This, therefore, means that we would have to provide those libraries under `RDEPEND`, such as `bytestring`. As for negative interactions between libraries, I am unsure.

Given that this would be a change requiring fundamental changes in the way we handle core libraries, one way or another, this is largely a thought-bubble for the moment and hardly a pressing concern. But thoughts are welcome.

**Comment by trofi** [comment]
Fun fact: we don't have nice `BDEPEND`/`RDEPEND` story even for `gcc` itself. People have to manually copy `libgcc`, `libatomic` or `libstdc++` to the target to make final result work as we don't have library-only version of depends (https://bugs.gentoo.org/710378). On the bright side these libraries are frequently not needed by final binaries.

For GHC it's harder to follow the same pattern as packages have to be explicitly registered for the compiler. But might still be doable if we are to use two package databases in parallel: one is private cross-compiler database (for example `/usr/lib64/ia64-unknown-linux-gnu-ghc-8.11.0.20200703`, would contain only ghc's own libraries), and the second is target's database in ${SYSROOT}: `/usr/ia64-unknown-linux-gnu/usr/lib64/ia64-unknown-linux-gnu-ghc-8.11.0.20200703` (would contain all the libraries installed by cross-emerge). 

The result would still require people somehow supply `base` and friends but it would be closer to what we have for `gcc`.

**Comment by solpeth** [comment]
Very enlightening. Thank you! I have much to learn about.

**Comment by solpeth** [comment]
On that note I'm going to close this. Perhaps in the future I can revisit it.
