### ISSUE TITLE
Some dependency upperbounds are incorrect

### ISSUE THREAD

**Issue by ezzieyguywuf** [gentoo-haskell/hackport#79]
Specifically, as of `0.6.7.9999`, `hackport merge streamly-0.7.2` produces an incorrect upper-bound for `dev-haskell/primitive`

**Comment by solpeth** [comment]
Could you explain this a little more please? What upper bound did you get, and what upper bound did you expect?

**Comment by ezzieyguywuf** [comment]
I double checked by `ebuild streamly-0.7.2.0 ebuild prepare` and examining the cabal file - in the file, it lists `primitive-0.8` as the upperbound, but hackport produced `primitive-0.7.1`

**Comment by solpeth** [comment]
This is correct. There is [a hackage revision](https://hackage.haskell.org/package/streamly-0.7.2/revision/1.cabal) tightening the `primitive` upper bound down to 0.7.1. `hackport` always takes the latest revision from hackage.
