### ISSUE TITLE
`test-suite` detection fails if `test-suite` is not all lowercase

### ISSUE THREAD

**Issue by ezzieyguywuf** [gentoo-haskell/hackport#80]
As an example, `hackport merge cassava-0.5.2.0` does **not** generate the dependency list presented in the `Test-suite` stanza in `cassava.cabal`. Notice the capital "T" in `Test-suite`

**Comment by trofi** [comment]
The problem is in not in casesensitivity (hackport uses `Cabal` directly to parse `.cabal` files, syntax handling should be mostly correct), but in dependencies conditional on `ghc` version:

```
  if impl(ghc >= 8.0)
    ghc-options: -Wcompat -Wnoncanonical-monad-instances -Wnoncanonical-monadfail-instances
  else
    -- provide/emulate `Control.Monad.Fail` and `Data.Semigroups` API for pre-GHC8
    build-depends: fail, semigroups
```

Hackport infers lower bound lower than `ghc-8.0` and does not pull those in.

**Comment by solpeth** [comment]
Closing as it seems 'fixed' by referenced commit.
