### ISSUE TITLE
Should hackport check for invalid HOMEPAGE?

### ISSUE THREAD

**Issue by ezzieyguywuf** [gentoo-haskell/hackport#89]
`hackport merge converge-0.1.0.1` results in an ebuild with `HOMEPAGE="/dev/null"`, which is exactly what is listed on hackage.

[repoman flags this](https://github.com/gentoo-haskell/gentoo-haskell/pull/1155/checks?check_run_id=1929310243#step:6:13) as an error.

Should hackport attempt to parse the URL and "do something else" if it is invalid?

**Comment by trofi** [comment]
I think hackport already runs `repoman` automatically that should flag a problem. Ideally such problems should be reported and fixed upstream.

For licenses `hackport` tries to preserve a license from older ebuilds if newer ones provide a license `hackport` does not understand. `HOMEPAGE` could follow the same suit if it fails to be parsed as an URI. Perhaps also worth reporting to `Cabal` upstream if `cabal check` does not reject such packages yet.

**Comment by hololeap** [comment]
I agree that we should try to translate this from the `.cabal` file to the `.ebuild` verbatim, and this falls outside of `hackport`'s scope.

**Comment by hololeap** [comment]
> Should hackport attempt to parse the URL and "do something else" if it is invalid?

This "do something else" thorn is why 😉

**Comment by solpeth** [comment]
Agreed - this is pkgcheck's domain.
